spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      #      schemaLocations: classpath:h2/schema.sql
      dataLocations: classpath:h2/data.sql
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # 연관관계 Lazy 사용 시 JPA 또는 QueryDsl에서 데이터 문제없이 가져오기 위해 설정
        default_batch_fetch_size: 500
    defer-datasource-initialization: true
    open-in-view: false

server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  port: 8080